### ISSUE TITLE
DDOS attack still pass through

### ISSUE THREAD

**Issue by devfalafel** [SirPlease/IPTables#1]
Hi,

I have been using this Iptables file for my game server (L4D) but some attacks still pass through. Recently I have captured it using tcpdump and tried to analyze it in Wireshark. The packet length is usually 50 Bytes with an error spamming in the game server console **"Invalid split packet length 8"**. The traffic per second is **265 kbps** and **~15000 packets/ 30 seconds**. I have 5 pcap files that showed legit players usually only send up to **~5000 packets/30 seconds** while DDOS attacks use so much more (in my case 15000 is the minimum). I wonder if we should add rules that use hit count such as this? Or if there is already a reason why we don't already have that rule?

```
iptables -I INPUT -p udp --dport $UDP_PORTS_PROTECTION -m state --state NEW -m recent --set
iptables -I INPUT -p udp --dport $UDP_PORTS_PROTECTION -m state --state NEW -m recent --update --seconds 30 --hitcount 8000 -j DROP
```

I'm still new to Iptables and not sure how I would integrate this into your existing bash script. I tried to append it to your "UDPfilter" chain but I got this error below instead:  

```
iptables v1.8.7 (nf_tables):  RULE_APPEND failed (Invalid argument): rule in chain UDPfilter
``` 

Please help, thanks!

**Comment by SirPlease** [comment]
This repository is quite ancient, glancing over it now makes me realize that it has a lot of room for improvement and would let a lot of malicious traffic through.
I'm not interested in copying over my current setup as it'd open myself up to possible attacks, but I'll update this later today/tomorrow with an improved version.

As for the error you're experiencing, it's likely a syntax error, as you haven't provided the exact rule I can't verify it for you.
```
## Create Filter Rules
##---------------------
iptables -A UDPfilter -m state --state NEW -m recent --name NEW_PACKETS --set
iptables -A UDPfilter -m state --state NEW -m recent --name NEW_PACKETS --update --seconds 30 --hitcount 8000 -j DROP

iptables -A UDPfilter -m state --state NEW -m hashlimit --hashlimit-upto 1/sec --hashlimit-burst 5 --hashlimit-mode srcip,dstport --hashlimit-name UDPDOSPROTECT --hashlimit-htable-expire 60000 --hashlimit-htable-max 999999999 -j ACCEPT
```

I have to say though, these rules likely won't do much.
Something to keep in mind is that while UDP is a stateless protocol, `<IP>:<Port> -> <Server IP>:<Server Port>` combinations will be considered an established connection in UDP for 120-180 seconds (depending on your settings), as long as they were accepted by the server.
The duration will be refreshed if a new packet has been sent with this combination that has been accepted.
This means that actively connected players will be considered as `state ESTABLISHED`.

My apologies if I'm unclear in this post or have made some weird typos, I just really wanted to respond before I sign off to get some sleep.
If you'd like me to analyze the pcap files, you can send them to me privately through Discord (sirplease)
Simply send me a friend request on there~ :)

**Comment by devfalafel** [comment]
Hi,

Thanks for replying! I tried to add you but it said you are not accepting friend requests. I have dropped message in your discord channel #bug-glitch-reports.

Thanks!
